### ISSUE TITLE
Could you add a license to your repo?

### ISSUE THREAD

**Issue by homebysix** [opragel/OSX_Scripts#1]
My organization would like to use and modify some of your scripts, but the absence of a license prevents us from doing so. Could you add one?

Thank you!

**Comment by opragel** [comment]
Done. I just want to officially note here that most of these haven't been updated in some time and I no longer advocate for using many of the - but feel free to borrow what you like.

https://github.com/opragel/OSX_Scripts/blob/master/LICENSE.
